# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learner', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% ../app.ipynb 3
learner = load_learner("export.pkl")

# %% ../app.ipynb 6
def classify_image(img):
    pred,pred_idx,probs = learner.predict(img)
    return dict(zip(learner.dls.vocab,map(float,probs)))


# %% ../app.ipynb 8
image = gr.inputs.Image(shape = (224,224))
label = gr.outputs.Label()
examples = ["grizzly.jpg"]
intf = gr.Interface(fn=classify_image,inputs =image, outputs=label, examples =examples )
intf.launch(inline=False)
